In [1]:
import numpy as np

In [39]:
# Write a function that uses "for" loops to multiply a mxm matrix A with a mx1 column vector x
# This would replicate how you would multiply these items "by hand"
def f(A, x):
    '''
    do stuff here
    '''
    (rows, cols) = A.shape

    b = np.empty(rows)
    for i in range(0, rows):
    	q = 0
    	for j in range(0, cols):
    		q += A[i,j] * x[j]
    	b[i] = q
	
    return b

In [10]:
def createSquareMatrix(m, low=1, high=10, invertable=False):
    '''
    Returns a square matrix with integer values
    m = size of matrix
    low = smallest integer value to appear in matrix.  inclusive.
    high = largest integer value to appear in matrix.  inclusive.
    invertable = Should the generated matrix be created such that it has an inverse?
    '''
    # Generate a random mxm matrix
    random_matrix = np.random.randint(low=low, high=high+1, size=(m, m)) # low inclusive, high exclusive

    if (invertable):
        # Extract the upper triangle
        return np.triu(random_matrix)
    else:
        return random_matrix
        
    # print("\nUpper triangular matrix (top-left 5x5):\n", A[:5, :5])

def createVector(m, low=1, high=10):
    return np.random.randint(low=low, high=high+1, size=m)

In [33]:
A = createSquareMatrix(90, low=1, high=10)
x = createVector(90, 1, 5)

# Show subset of elements:
A[:5, :5], x[:5]

(array([[ 8,  3,  2,  3,  8],
        [ 5,  7,  7,  2, 10],
        [ 8,  1, 10,  2,  6],
        [ 6,  5, 10,  3,  4],
        [ 7,  6,  8,  3,  8]]),
 array([2, 1, 4, 3, 4]))

In [40]:
# Call your function and display the result
f(A,x)

array([1616., 1752., 1549., 1667., 1523., 1467., 1624., 1591., 1639.,
       1628., 1548., 1499., 1546., 1558., 1657., 1495., 1524., 1575.,
       1729., 1762., 1521., 1617., 1483., 1513., 1508., 1667., 1454.,
       1462., 1704., 1441., 1589., 1669., 1687., 1626., 1672., 1610.,
       1697., 1548., 1628., 1484., 1527., 1521., 1549., 1577., 1579.,
       1609., 1601., 1578., 1562., 1472., 1465., 1701., 1539., 1573.,
       1671., 1649., 1556., 1482., 1448., 1615., 1443., 1653., 1465.,
       1583., 1495., 1700., 1582., 1517., 1661., 1464., 1611., 1533.,
       1540., 1454., 1629., 1426., 1499., 1535., 1400., 1606., 1608.,
       1742., 1605., 1648., 1616., 1536., 1827., 1596., 1654., 1666.])

In [42]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [43]:
x = np.array([5, 6])
x

array([5, 6])

In [44]:
f(A, x)

array([17., 39.])

In [47]:
np.matmul(A, x)

array([17, 39])

In [48]:
A = createSquareMatrix(900, low=1, high=10)
x = createVector(900, 1, 5)

# Show subset of elements:
A[:5, :5], x[:5]

(array([[ 3,  1,  6,  3,  7],
        [ 9,  6,  6,  8, 10],
        [ 6, 10,  6,  7,  9],
        [ 1, 10,  8,  9,  7],
        [ 5, 10,  9,  7, 10]]),
 array([2, 4, 5, 4, 3]))

In [49]:
%timeit f(A,x)

221 ms ± 2.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [50]:
%timeit np.matmul(A, x)

874 µs ± 28.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Some helpful info

In [35]:
# len only gives one dimension:
len(A)

90

In [22]:
# Shape is more useful:
(rows, cols) = A.shape
rows, cols

(90, 90)

In [32]:
# Shape for a vector:
x.shape

(90,)

In [29]:
q = np.empty(shape=90, dtype=float)
r = np.arange(1,10)
q, r

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [30]:
r[2] = 55
r

array([ 1,  2, 55,  4,  5,  6,  7,  8,  9])

In [36]:
A

array([[ 8,  3,  2, ...,  4,  7,  9],
       [ 5,  7,  7, ...,  9, 10,  4],
       [ 8,  1, 10, ...,  5,  1,  5],
       ...,
       [10,  3,  1, ...,  4,  8,  4],
       [ 4,  1,  4, ...,  6,  5,  3],
       [ 8,  9,  5, ...,  8,  9,  8]])

In [37]:
# 2nd row, 3 column of A:
A[1][2]

np.int64(7)

In [38]:
A[1, 2]

np.int64(7)